services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prom-config.yaml:/etc/prometheus/prometheus.yaml
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'

  app:
    build:
      context: microservice
    ports:
      - "8080:8080"

volumes:
  prometheus-data:
  grafana_storage: