- name: Копировать compose.yaml
  copy:
    src: "{{ playbook_dir }}/roles/microservice/templates/compose.yaml.j2"
    dest: /opt/microservice/compose.yaml

- name: Запуск docker compose
  shell: docker compose up -d
  args:
    chdir: "{{ docker_compose_path }}"
