- name: Копировать бинарник
  copy:
    src: "{{ playbook_dir }}/../build/microservice"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Установить systemd unit из шаблона
  template:
    src: microservice.service.j2
    dest: /etc/systemd/system/microservice.service

- name: Перезапустить systemd unit
  systemd:
    name: "{{ microservice_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
